# Generated by Django 3.1.5 on 2021-01-08 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
