# Generated by Django 3.1.5 on 2021-01-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.TextField(db_index=True, max_length=300, unique=True),
        ),
    ]
